### ISSUE TITLE
Improvements to match our desired open-source release workflow

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/github-changelog-generator#1]
We want the changes to the CHANGELOG.md file to be reflected in the upcoming release.
Basically, the workflow we would like to have is this:

1. create an issue on github with a title similar to "Version Bump"
2. open a branch to work on that issue
3. push commits to that branch **updating the changelog to include the upcoming release with its proper number** and any other place in the project where such number should change (e.g. [app-name].app.src in erlang projects)
4. create a PR with those changes
5. once that PR is merged, generate a release with the desired number

We would like github-changelog-generator to let us make the changes required for item 3 automatically by doing something like:
```sh
github_changelog_generator --token [GITHUB-TOKEN] --future-release [RELEASE-VERSION]
```

That new parameter (`--future-release`) should be used as the title for the section currently known as `Unreleased` and it's urls should be changed accordingly.

**Comment by jfacorro** [comment]
+1
